spring.application.name=flyway



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
    

amadeus.client-id=${AMADEUS_CLIENT_ID}
amadeus.client-secret=${AMADEUS_CLIENT_SECRET}
